### ISSUE TITLE
Consider these design improvements:

### ISSUE THREAD

**Issue by jabTheGeek** [skunkforce/b081_I2C_4x_diff_ADC_MCP3428#2]
1.     Add copper pours (<30 % riight now)
2.     Increase spacing
3.     Separate AD3 and AD4
4.     Check SDA/SCL pull-ups
5.     Add ESD protection
6.     Use a beefier VDD cap
7.     Add VDD input filter
8.     Label VDD/address selection

**Comment by odinthenerd** [comment]
Thanks for your input, some of these points may be stemming from a lack of documentation in the edgy_board or put_on_edge documentation.

4. as per the edgy_board concept pull-ups are always on the master end so no slave should need pull ups. 

5. the chip has 2kv human body model, beyond this is not needed for edgys as they are not deployed in the field and not all designed utilizing this edgy will need stronger ESD protection (it could be measuring something internal to the PCB)

7. not a bad idea in this case but generally the topic of power integrity is not part of the edgy ecosystem but should be considered only when using edgies in composition.

The other points should be fixed.

**Comment by odinthenerd** [comment]
This was good input, and the board looks better now. 

Check out the newest commit in #1 

I'm not sure what you meant by "Separate AD3 and AD4"

**Comment by jabTheGeek** [comment]
Thanks for the feedback. The updated design really looks better now.
What I wanted to say was that AD3 and AD4 could be routed a little bit farther away from each other, but the routing impact will be minimal compared to breaking out the signal on the edgy. Looking forward to test them.
